# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-16 12:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='create_time',
            field=models.DateField(default=datetime.datetime.now, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='article',
            name='modify_time',
            field=models.DateField(default=datetime.datetime.now, verbose_name='修改时间'),
        ),
    ]
