# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-16 12:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170816_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='create_time',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='article',
            name='modify_time',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='修改时间'),
        ),
    ]
